name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Make
      run: |
        cd driver
        make -j $(nproc) KDIR="/lib/modules/$(uname -r)/build" all
